swagger: "2.0"
info:
  title: Topic API
  description: "This service is used to retrieve information about the topics used to categorise ONS data.
  
  Note: As of the latest update, the `@context` field has been removed from all topics endpoints to improve response performance and correct data structure."
  version: 1.0.0
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
basePath: "/v1"
schemes:
  - http
tags:
  - name: "Public"
  - name: "Private"
parameters:
  id:
    name: id
    in: path
    required: true
    description: "The ID of a topic."
    type: string
    example: "1234"
  type:
    description: "An option to select a subset of the possible types of content returned."
    name: type
    in: query
    required: false
    type: string
    enum: ["spotlight", "articles", "bulletins", "methodologies", "methodologyarticles", "staticdatasets", "timeseries", "publications", "datasets"]
  lang:
    name: lang
    description: "the 2 character code of the language required in returned labels, e.g. cy for welsh"
    in: query
    type: string
    required: false
  state:
    name: state
    description: "An update to the topics release date"
    type: string
    in: path
    required: true
  update_release_date:
    name: release_date
    description: "An update to the topics release date"
    in: body
    required: true
    schema:
      $ref: "#/definitions/TopicRelease"
  topic_update:
    name: topic_update
    in: body
    required: true
    schema:
      $ref: "#/definitions/TopicUpdate"
paths:
  /topics:
    get:
      tags:
        - "Public"
      summary: "Get a list of topics"
      description: "Gets a public list of top-level root topics."
      produces:
        - "application/json"
      responses:
        200:
          description: "JSON object containing a list of all available root topics."
          schema:
            $ref: '#/definitions/ListOfTopics'
        500:
          $ref: '#/responses/InternalError'

  /topics/{id}:
    get:
      tags:
        - "Public"
      summary: "Get a topic by ID"
      description: "Provides a high-level description of the topic and relevant links."
      parameters:
        - $ref: '#/parameters/id'
      produces:
        - "application/json"
      responses:
        200:
          description: "JSON object containing information about the topic."
          schema:
            $ref: '#/definitions/Topic'
        404:
          $ref: '#/responses/NotFound'
        500:
          $ref: '#/responses/InternalError'

    put:
      tags:
        - "Private"
      summary: "Update the topic details"
      description: "Updates a topic's details for the next nested object."
      parameters:
        - $ref: '#/parameters/id'
        - $ref: '#/parameters/topic_update'
      responses:
        200:
          description: "Success"
        400:
          $ref: '#/responses/BadRequest'
        401:
          $ref: '#/responses/Unauthorised'
        404:
          $ref: '#/responses/NotFound'
        500:
          $ref: '#/responses/InternalError'

  /topics/{id}/release-date:
    put:
      tags:
        - "Private"
      summary: "Update the topic release date"
      description: "Updates a topic's release date against the next nested object. Unavailable to view by public endpoints until published, ('next' object overwrites 'current' object)"
      parameters:
        - $ref: '#/parameters/id'
        - $ref: '#/parameters/update_release_date'
      responses:
        200:
          description: "Success"
        400:
          $ref: '#/responses/BadRequest'
        401:
          $ref: '#/responses/Unauthorised'
        404:
          description: '#/responses/NotFound'
        400:
          description: | 
            Bad request, messages could be 1 of the following:
            * request body empty
            * invalid topic release date, must use **RFC3339** format
        500:
          $ref: '#/responses/InternalError'

  /topics/{id}/state/{state}:
    put:
      tags:
        - "Private"
      summary: "Update the topic state"
      description: "Updates a topic's state against the next nested object. If state is equal to 'published', than the next object copies over to current object"
      parameters:
        - $ref: '#/parameters/id'
        - $ref: '#/parameters/state'
      responses:
        200:
          description: "Success"
        400:
          $ref: '#/responses/BadRequest'
        401:
          $ref: '#/responses/Unauthorised'
        404:
          $ref: '#/responses/NotFound'
        500:
          $ref: '#/responses/InternalError'

  /topics/{id}/subtopics:
    get:
      tags:
        - "Public"
      summary: "Get a list of subtopics"
      description: "Get a list of all documents for the specified ID contained in the stored list of subtopics."
      parameters:
        - $ref: '#/parameters/id'
      produces:
        - "application/json"
      responses:
        200:
          description: "JSON object containing an array of subtopics."
          schema:
            $ref: '#/definitions/ListOfTopics'
        404:
          $ref: '#/responses/NotFound'
        500:
          $ref: '#/responses/InternalError'

  /topics/{id}/content:
    get:
      tags:
        - "Public"
      summary: "Get a list of content"
      description: "Get a list of different content types for the specified ID."
      parameters:
        - $ref: '#/parameters/id'
        - $ref: '#/parameters/type'
      produces:
        - "application/json"
      responses:
        200:
          description: "JSON object containing an array(s) of content types."
          schema:
            $ref: '#/definitions/ListOfContent'
        400:
          $ref: '#/responses/BadRequest'
        404:
          $ref: '#/responses/NotFound'
        500:
          $ref: '#/responses/InternalError'

  /navigation:
    get:
      tags:
        - "Public"
      summary: "Get a list for navigation"
      description: "Get a list of topics for site navigation"
      produces:
        - "application/json"
      parameters:
        - $ref: '#/parameters/lang'
      responses:
        200:
          description: "Provides a hierarchical list of navigation items with their links, copy, and localisation references."
          schema:
            $ref: '#/definitions/Navigation'
          headers:
            Cache-Control:
              default: "public, max-age=1800"
              type: string
              description: "Caching information for the response."
        500:
          $ref: '#/responses/InternalError'
responses:
  InternalError:
    description: "Failed to process the request due to an internal error."

  Unauthorised:
    description: "Failed to process the request due to being unauthorised."

  NotFound:
    description: "The specified resource was not found."

  BadRequest:
    description: "The request was invalid."

definitions:
  Content:
    type: object
    properties:
      links:
        type: object
        properties:
          self:
            $ref: '#/definitions/SelfHref'
          topic:
            $ref: '#/definitions/TopicLink'
      state:
        $ref: '#/definitions/State'
      title:
        type: string
        description: "Title of the information."
      type:
        type: string
        description: "Name of the containing type."

  Topic:
    type: object
    properties:
      description:
        type: string
        description: "A description of the topic."
      id:
        type: string
        description: "The ID of the topic."
      keywords:
        type: array
        items:
          type: string
        description: "List of keywords that relate to the topic."
      links:
        type: object
        properties:
          self:
            $ref: '#/definitions/SelfHref'
          subtopics:
            $ref: '#/definitions/SubtopicsLink'
          content:
            $ref: '#/definitions/ContentLink'
      slug:
        type: string
        description: "The slug of the topic."
        example: "businessindustryandtrade"
      state:
        $ref: '#/definitions/State'
      subtopics_ids:
        type: array
        items:
          type: string
        description: "Array of subtopic IDs."
      title:
        type: string
        description: "The title of the topic."
        example: "Business, Industry and Trade"

  SubtopicsLink:
    type: object
    description: "A link to the subtopics of this topic."
    properties:
      href:
        type: string
        description: "A URL to the subtopics of this topic."

  ContentLink:
    type: object
    description: "A link to the content for this topic."
    properties:
      href:
        type: string
        description: "A URL to the content for this topic."

  ListOfContent:
    type: object
    description: "A list of content items."
    properties:
      context:
        type: string
        description: "The URL to the context file."
        example: "https://cdn.ons.gov.uk/assets/json-ld/context.json"
      count:
        $ref: '#/definitions/Count'
      items:
        type: array
        items:
          $ref: '#/definitions/Content'
      limit:
        $ref: '#/definitions/Limit'
      offset_index:
        $ref: '#/definitions/Offset'
      total_count:
        $ref: '#/definitions/TotalCount'

  ListOfTopics:
    type: object
    description: "A list of topics."
    properties:
      context:
        type: string
        description: "The URL to the context file."
        example: "https://cdn.ons.gov.uk/assets/json-ld/context.json"
      count:
        $ref: '#/definitions/Count'
      items:
        type: array
        items:
          $ref: '#/definitions/Topic'
      limit:
        $ref: '#/definitions/Limit'
      offset_index:
        $ref: '#/definitions/Offset'
      total_count:
        $ref: '#/definitions/TotalCount'

  SelfHref:
    type: object
    properties:
      id:
        type: string
        description: "The ID of the resource."
      href:
        type: string
        description: "The URL to the resource."

  State:
    type: string
    description: "The state of the resource."
    enum:
      - created
      - published
      - completed

  TopicLink:
    type: object
    description: "A link to the topic for this content."
    properties:
      href:
        type: string
        description: "The URL to the topic."
      id:
        type: string
        description: "The ID for the topic that this content is associated with."

  Count:
    type: integer
    description: "The number of results returned in this response."

  TotalCount:
    type: integer
    description: "The total number of results available."

  Limit:
    type: integer
    description: "The limit applied to the number of results returned."

  Offset:
    type: integer
    description: "The offset applied to the number of results returned"
  Description:
    type: string
    description: "A human-readable description as a string"
  Name:
    type: string
    description: "A hyphenated reference to the item"
  Label:
    type: string
    description: "The label to be displayed to a user, translated based on the lang parameter"
  Title:
    type: string
    description: "A string containing the title of something"
  Uri:
    type: string
    description: "The path to the resource on the web domain"
  Navigation:
    type: object
    description: "Resource describing the structure for the ONS website navbar."
    properties:
      context:
        description: "The URL to the context file"
        type: string
        example: "https://cdn.ons.gov.uk/assets/json-ld/context.json"
      description:
        description: "A description of the navigation"
        type: string
      items:
        description: "An array of navigation items"
        type: array
        items:
          $ref: '#/definitions/ListOfNavigationItems'
      links:
        type: object
        properties:
          self:
            type: object
            properties:
              href:
                type: string
                description: "The URL to the resource"
  TopicRelease:
    type: object
    description: "Object containing topic release details."
    properties:
      release_date:
        type: string
        format: date-time
        description: "The release date formatted to abide by RFC3339."
        example: "2022-10-10T08:30:00Z"

  TopicUpdate:
    type: object
    description: "Object containing topic data update."
    required:
      - title
      - slug
      - description
      - release_date
      - state
    properties:
      title:
        type: string
        description: "The title of a topic."
        example: "Business, Industry and Trade"
      slug:
        type: string
        description: "The slug of a topic."
        example: "businessindustryandtrade"
      description:
        type: string
        description: "The description of a topic."
        example: "Lots of information about business."
      release_date:
        type: string
        format: date-time
        description: "The release date formatted to abide by RFC3339."
        example: "2022-10-10T08:30:00Z"
      keywords:
        type: array
        items:
          type: string
        description: "List of keywords that relate to the topic."
      state:
        $ref: '#/definitions/State'
      subtopics_ids:
        type: array
        items:
          type: string
        description: "Array of subtopic ids"
  ListOfNavigationItems:
    type: array
    description: "A list of navigation items"
    items:
      type: object
      properties:
        description:
          $ref: '#/definitions/Description'
        label:
          $ref: '#/definitions/Label'
        links:
          type: object
          properties:
            self:
              $ref: '#/definitions/SelfHref'
        name:
          $ref: '#/definitions/Name'
        slug:
          description: "The slug of the item"
          type: string
        subtopics:
          type: array
          items:
            properties:
              description:
                $ref: '#/definitions/Description'
              label:
                $ref: '#/definitions/Label'
              links:
                type: object
                properties:
                  self:
                    $ref: '#/definitions/SelfHref'
              name:
                $ref: '#/definitions/Name'
              slug:
                description: "The slug of the item"        
                type: string
              title:
                $ref: '#/definitions/Title'
              uri:
                $ref: '#/definitions/Uri'
        title:
          $ref: '#/definitions/Title'
        uri:
          $ref: '#/definitions/Uri'