on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  new_pull_request:
    runs-on: ubuntu-latest
    name: Dump GitHub context
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - run: echo "$GITHUB_CONTEXT"
      - name: Send GitHub trigger payload to Slack Workflow Builder
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
